Develop term of use
pdariusv/howdy-group-project pull request #36
Opened 2020-07-28 21:23 UTC by Weltgeist

-Added term of use page and some content from a external source.
-Used handlebar instead of react.
-Couldn't find Luis static page so, I included it separately.

Any suggestion, on how to include it the react way is welcomed.

2020-07-29 06:06 UTC, luciancic requested changes
Congrats on your first PR! Nicely done. Just a few details to iron out before I can merge. Could you rename `StaticPage.js` to `TermsOfUse.js` and the imports, links and route. Also see my comment on the `article` attributes. If u have questions about updating the PR and the review process you know where to find me. Thanks!

2020-07-29 06:06 UTC, luciancic commented on client/src/components/Forum/StaticPage.js
> +            <article id="ownership">
The `id` attribute can come from `term.name` and it needs a `key` attribute that you can set with `idx`. See [react lists and keys on why](https://reactjs.org/docs/lists-and-keys.html) on why.

2020-08-11 19:11 UTC, Weltgeist commented on client/src/components/Forum/StaticPage.js
> +            <article id="ownership">
i did, thx. I also made some refactoring, added another functional react element

2020-08-11 19:13 UTC, Weltgeist commented on client/src/components/Forum/StaticPage.js
> +            <article id="ownership">
term:
590b630 
id:
d021fa1

2020-08-11 22:48 UTC, luciancic commented
Delete terms-of-use.html
Style the link and the content using basic materialUI components
Replace terms of use with privacy policy and code of conduct (separate page) content.

2020-08-18 23:11 UTC, luciancic commented
Closing because this seems to be going off on a tangent and a term of use is overkill on an app of this scope.

2020-08-18 23:11 UTC, closed without merging